name: CD Pipeline for backends

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: deploy backends to docker_hub and then to EC2
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo 
        uses: actions/checkout@v4
      
      - name: login in to docker hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build ws be and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/ws.dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tui-typer-be:latest

      - name: deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd tui-typer-ws$
            sudo docker compose down -v
            sudo docker system prune -a -f --volumes
            sudo docker builder prune -a -f
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
      